# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: brettt89/silverstripe-web
        environment:
          - SS_DATABASE_CLASS=MySQLPDODatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=test
          - YUBIAUTH_CLIENTID=12345
          - YUBIAUTH_APIKEY=VGhpc0lzUmVhbGx5QVZhbGlkS2V5
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: ~/var/www

    steps:
      # Install additional requirements
      - run:
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            php -r "unlink('composer-setup.php');"

      - checkout
      - run: cp ~/var/www/_config/config.yml.example ~/var/www/_config/config.yml
      # Composer Cache, Yarn and non-vendor modules
      - restore_cache:
          keys:
            - v2-cache-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-cache-
      # update, because why not
      - run: composer update
      - run: cp -r vendor/silverstripe/recipe-cms/mysite .
      # Save all dependencies to cache
      - save_cache:
          key: v2-cache-{{ checksum "composer.lock" }}
          paths:
            - assets
            - vendor
      - run: vendor/bin/sake dev/build

      # run tests!
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml -d memory_limit=512M tests/unit
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.xml
      - run: wget https://scrutinizer-ci.com/ocular.phar
      - run: php ocular.phar code-coverage:upload --access-token="5c25ea9106f1b0fb619192dfa699f833124a0e18a0263519eb2208b5d7f64116" --format=php-clover coverage.clover