---
name: MFAAuthenticator
After:
  - #coresecurity
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: %$Firesphere\BootstrapMFA\Authenticators\BootstrapMFAAuthenticator
SilverStripe\Security\Member:
  extensions:
    - Firesphere\BootstrapMFA\Extensions\MemberExtension
Firesphere\BootstrapMFA\Models\BackupCode:
  token_limit: 15
Firesphere\BootstrapMFA\Generators\CodeGenerator:
  length: 6
  type: mixed
  case: mixed
Firesphere\BootstrapMFA\Authenticators\BootstrapMFAAuthenticator:
  grace_period: 14
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Firesphere\BootstrapMFA\Extensions\SiteConfigExtension